//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSell
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class car_shopEntities : DbContext
    {
        public car_shopEntities()
            : base("name=car_shopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts1 { get; set; }
        public virtual DbSet<Basket> Baskets1 { get; set; }
        public virtual DbSet<Car> Cars1 { get; set; }
        public virtual DbSet<Coupon> Coupons1 { get; set; }
        public virtual DbSet<Favorite> Favorites1 { get; set; }
        public virtual DbSet<Phistory> Phistories1 { get; set; }
    }
}
